/* ═══════════════════════════════════════════════════════
   ДАЧНЫЙ ДОМ — КОНФИГУРАЦИЯ И ДАННЫЕ ТОВАРОВ
   ═══════════════════════════════════════════════════════ */

const CONFIG = {
  telegramBotToken: '8375682326:AAEpPXV_x6Favd3ilILhG69Jf3i6Rgqy_kg',
  telegramChatId: '936226082',
  googleScriptUrl: '',
  yookassaShopId: '',
  yookassaReturnUrl: '',
  shopName: 'Дачный Дом',
  shopPhone: '+7 (999) 310-84-96',
  shopEmail: 'td-class@mail.ru',
  shopAddress: 'Махачкала, ул. Ярагского, 23',
  shopWorkHours: 'Пн–Сб 9:00–18:00',
  freeDeliveryFrom: 15000,
  deliveryPrice: 990,
  currency: '₽',
};

const CATEGORIES = [
  { id: 'all',     name: 'Все товары' },
  { id: 'swings',  name: 'Садовые качели' },
  { id: 'gazebos', name: 'Беседки' },
  { id: 'loungers',name: 'Шезлонги' },
  { id: 'sets',    name: 'Комплекты мебели' },
  { id: 'dining',  name: 'Столовые группы' },
  { id: 'terrace', name: 'Терраса' },
  { id: 'storage', name: 'Хранение' },
];

const PRODUCTS = [
  {
    id: 1,
    category: 'swings',
    name: 'Качели «Пальмира»',
    price: 49990,
    oldPrice: 62000,
    image: 'images/products/001-palmira/img1.jpg',
    images: [
      'images/products/001-palmira/img1.jpg',
      'images/products/001-palmira/img2.jpg',
      'images/products/001-palmira/img3.jpg',
      'images/products/001-palmira/img4.jpg',
    ],
    description: 'Просторные беседка-качели для комфортного отдыха всей семьи. Прочный металлический каркас устойчив к нагрузкам и погодным условиям. Мягкие подушки и защитный тент обеспечивают удобство в течение всего сезона.',
    badge: 'sale',
    rating: 4.8,
    reviews: 47,
    inStock: true,
    features: ['Материал: сосна', 'Нагрузка: до 200 кг', 'Подушки в комплекте', 'Сборка: 30 мин'],
  },
  {
    id: 2,
    category: 'swings',
    name: 'Качели «Ибица»',
    price: 25990,
    oldPrice: null,
    image: 'images/products/002-ibitsa/img1.jpg',
    images: [
      'images/products/002-ibitsa/img1.jpg',
    ],
    description: 'Современные садовые качели с мягким сиденьем и регулируемой спинкой. Надёжный каркас выполнен из стальной трубы с защитным покрытием. Отлично подходят для дачи, террасы и зоны отдыха на участке.',
    badge: 'new',
    rating: 4.9,
    reviews: 23,
    inStock: true,
    features: ['Каркас: металл', 'Тент: полиэстер', 'Нагрузка: до 250 кг', 'Размер: 180×120×170 см'],
  },
  {
    id: 3,
    category: 'swings',
    name: 'Качели «Мерида»',
    price: 34690,
    oldPrice: null,
    image: 'images/products/003-merida/img1.jpg',
    images: [
      'images/products/003-merida/img1.jpg',
      'images/products/003-merida/img2.jpg',
      'images/products/003-merida/img3.jpg',
      'images/products/003-merida/img4.jpg',
    ],
    description: 'Премиальная модель с увеличенным посадочным местом и усиленной конструкцией. Комфортные подушки обеспечивают удобную посадку даже при длительном отдыхе. Подходит для круглогодичного использования под навесом.',
    badge: 'hit',
    rating: 4.7,
    reviews: 89,
    inStock: true,
    features: ['Материал: клееный брус', 'Площадь: 16 м²', 'Вместимость: 10 чел.', 'Сборка включена'],
  },
  {
    id: 4,
    category: 'swings',
    name: 'Качели «Ренессанс»',
    price: 25990,
    oldPrice: null,
    image: 'images/products/004-renesans/img1.jpg',
    images: [
      'images/products/004-renesans/img1.jpg',
      'images/products/004-renesans/img2.jpg',
      'images/products/004-renesans/img3.jpg',
      'images/products/004-renesans/img4.jpg',
    ],
    description: 'Элегантные качели классического дизайна для сада и загородного дома. Прочный каркас выдерживает высокие нагрузки и сохраняет устойчивость. Тент защищает от солнца и лёгкого дождя.',
    badge: '',
    rating: 4.5,
    reviews: 34,
    inStock: true,
    features: ['Москитная сетка', 'Каркас: алюминий', 'Размер: 3×3 м', 'Вес: 8 кг'],
  },
  {
    id: 5,
    category: 'swings',
    name: 'Качели «Империя»',
    price: 43990,
    oldPrice: null,
    image: 'images/products/005-imperia/img1.jpg',
    images: [
      'images/products/005-imperia/img1.jpg',
      'images/products/005-imperia/img2.jpg',
      'images/products/005-imperia/img3.jpg',
      'images/products/005-imperia/img4.jpg',
    ],
    description: 'Надёжные трёхместные качели с мягкими подушками и удобной посадкой. Каркас изготовлен из прочной стали с антикоррозийной обработкой. Идеальный вариант для семейного отдыха на свежем воздухе.',
    badge: 'sale',
    rating: 4.6,
    reviews: 112,
    inStock: true,
    features: ['Материал: текстилен', 'Каркас: алюминий', '5 позиций', 'Нагрузка: 150 кг'],
  },
  {
    id: 6,
    category: 'swings',
    name: 'Качели «Империя Люкс»',
    price: 24990,
    oldPrice: null,
    image: 'images/products/006-imperia/img1.jpg',
    images: [
      'images/products/006-imperia/img1.jpg',
      'images/products/006-imperia/img2.jpg',
      'images/products/006-imperia/img3.jpg',
      'images/products/006-imperia/img4.jpg',
    ],
    description: 'Улучшенная версия популярной модели с увеличенным уровнем комфорта. Оснащена плотными подушками и надёжным механизмом раскладывания. Подходит для ежедневного использования на даче и террасе.',
    badge: 'new',
    rating: 4.9,
    reviews: 18,
    inStock: true,
    features: ['2 места', 'Столик в комплекте', 'Влагостойкие подушки', 'Раскладной'],
  },
  {
    id: 7,
    category: 'swings',
    name: 'Качели «Амаре»',
    price: 49990,
    oldPrice: 69990,
    image: 'images/products/007-amare/img1.jpg',
    images: [
      'images/products/007-amare/img1.jpg',
      'images/products/007-amare/img2.jpg',
      'images/products/007-amare/img3.jpg',
      'images/products/007-amare/img4.jpg',
    ],
    description: 'Беседка-качели премиального класса с просторным посадочным местом. Конструкция сочетает функции садовой беседки и комфортной зоны отдыха. Защитный навес создаёт приятную тень даже в жаркий день.',
    badge: 'sale',
    rating: 4.8,
    reviews: 56,
    inStock: true,
    features: ['Тик высший сорт', 'Стол + 4 кресла + скамья', 'Подушки в комплекте', 'Гарантия 5 лет'],
  },
  {
    id: 8,
    category: 'swings',
    name: 'Качели «Таити»',
    price: 8190,
    oldPrice: null,
    image: 'images/products/008-taiti/img1.jpg',
    images: [
      'images/products/008-taiti/img1.jpg',
      'images/products/008-taiti/img2.jpg',
      'images/products/008-taiti/img3.jpg',
      'images/products/008-taiti/img4.jpg',
    ],
    description: 'Компактная модель для небольших садовых участков и дач. Лёгкая конструкция упрощает установку и перемещение. Практичное решение для комфортного отдыха на открытом воздухе.',
    badge: 'hit',
    rating: 4.7,
    reviews: 73,
    inStock: true,
    features: ['Искусственный ротанг', '5 модулей', 'Ткань Sunbrella', 'Любая конфигурация'],
  },
  {
    id: 9,
    category: 'swings',
    name: 'Качели «Паттайя»',
    price: 34690,
    oldPrice: null,
    image: 'images/products/009-pataya/img1.jpg',
    images: [
      'images/products/009-pataya/img1.jpg',
      'images/products/009-pataya/img2.jpg',
      'images/products/009-pataya/img3.jpg',
      'images/products/009-pataya/img4.jpg',
    ],
    description: 'Стильные качели с современным дизайном и удобным мягким сиденьем. Усиленный металлический каркас обеспечивает долговечность конструкции. Отлично вписываются в современные ландшафтные проекты.',
    badge: 'sale',
    rating: 4.4,
    reviews: 203,
    inStock: true,
    features: ['Размер: 120×60 см', 'Алюминиевые ножки', 'Чехол в комплекте', 'Вес: 5 кг'],
  },
  {
    id: 10,
    category: 'swings',
    name: 'Качели «Ибица Green»',
    price: 25990,
    oldPrice: null,
    image: 'images/products/010-ibitsa-green/img1.jpg',
    images: [
      'images/products/010-ibitsa-green/img1.jpg',
      'images/products/010-ibitsa-green/img2.jpg',
      'images/products/010-ibitsa-green/img3.jpg',
      'images/products/010-ibitsa-green/img4.jpg',
    ],
    description: 'Популярная модель в зелёном цветовом исполнении для сада и загородного дома. Удобное сиденье и прочный каркас обеспечивают комфортную эксплуатацию. Защитный тент помогает укрыться от солнца в жаркую погоду.',
    badge: '',
    rating: 4.9,
    reviews: 31,
    inStock: true,
    features: ['Размер: 160×80 см', 'Каркас: нержавейка', 'HPL столешница', 'Разборный'],
  },
  {
    id: 11,
    category: 'swings',
    name: 'Качели «Барселона»',
    price: 22000,
    oldPrice: null,
    image: 'images/products/011-barselona/img1.jpg',
    images: [
      'images/products/011-barselona/img1.jpg',
      'images/products/011-barselona/img2.jpg',
      'images/products/011-barselona/img3.jpg',
      'images/products/011-barselona/img4.jpg',
    ],
    description: 'Комфортные садовые качели с мягкими подушками и устойчивой конструкцией. Подходят для размещения на даче, террасе или в саду. Современный дизайн гармонично сочетается с любым экстерьером.',
    badge: 'sale',
    rating: 4.6,
    reviews: 88,
    inStock: true,
    features: ['Натуральный ротанг', 'Подушка в комплекте', 'Нагрузка: 120 кг', 'Для улицы и дома'],
  },
];
