/* ═══════════════════════════════════════════════════════
   ДАЧНЫЙ ДОМ — КОНФИГУРАЦИЯ И ДАННЫЕ ТОВАРОВ
   ═══════════════════════════════════════════════════════ */

const CONFIG = {
  telegramBotToken: '8375682326:AAEpPXV_x6Favd3ilILhG69Jf3i6Rgqy_kg',
  telegramChatId: '936226082',
  googleScriptUrl: '',
  yookassaShopId: '',
  yookassaReturnUrl: '',
  shopName: 'Дачный Дом',
  shopPhone: '+7 (999) 310-84-96',
  shopEmail: 'td-class@mail.ru',
  shopAddress: 'Махачкала, ул. Ярагского, 23',
  shopWorkHours: 'Пн–Сб 9:00–18:00',
  freeDeliveryFrom: 15000,
  deliveryPrice: 990,
  currency: '₽',
};

const CATEGORIES = [
  { id: 'all',     name: 'Все товары' },
  { id: 'swings',  name: 'Садовые качели' },
  { id: 'gazebos', name: 'Беседки' },
  { id: 'loungers',name: 'Шезлонги' },
  { id: 'sets',    name: 'Комплекты мебели' },
  { id: 'dining',  name: 'Столовые группы' },
  { id: 'terrace', name: 'Терраса' },
  { id: 'storage', name: 'Хранение' },
];

const PRODUCTS = [
  {
    id: 1,
    category: 'swings',
    name: 'Качели «Пальмира»',
    price: 49990,
    oldPrice: 62000,
    image: 'images/products/001-palmira/img1.jpg',
    images: [
      'images/products/001-palmira/img1.jpg',
      'images/products/001-palmira/img2.jpg',
      'images/products/001-palmira/img3.jpg',
      'images/products/001-palmira/img4.jpg',
    ],
    description: 'Уютные садовые качели из массива сосны. Прочная конструкция выдерживает до 200 кг. Мягкие подушки в комплекте.',
    badge: 'sale',
    rating: 4.8,
    reviews: 47,
    inStock: true,
    features: ['Материал: сосна', 'Нагрузка: до 200 кг', 'Подушки в комплекте', 'Сборка: 30 мин'],
  },
  {
    id: 2,
    category: 'swings',
    name: 'Качели «Ибица»',
    price: 29990,
    oldPrice: null,
    image: 'images/products/002-ibitsa/img1.jpg',
    images: [
      'images/products/002-ibitsa/img1.jpg',
      'images/products/002-ibitsa/img2.jpg',
      'images/products/002-ibitsa/img3.jpg',
      'images/products/002-ibitsa/img4.jpg',
    ],
    description: 'Элегантные качели в стиле прованс с защитным тентом. Металлический каркас с антикоррозийным покрытием.',
    badge: 'new',
    rating: 4.9,
    reviews: 23,
    inStock: true,
    features: ['Каркас: металл', 'Тент: полиэстер', 'Нагрузка: до 250 кг', 'Размер: 180×120×170 см'],
  },
  {
    id: 3,
    category: 'swings',
    name: 'Качели «Мерида»',
    price: 89990,
    oldPrice: 110000,
    image: 'images/products/003-merida/img1.jpg',
    images: [
      'images/products/003-merida/img1.jpg',
      'images/products/003-merida/img2.jpg',
      'images/products/003-merida/img3.jpg',
      'images/products/003-merida/img4.jpg',
    ],
    description: 'Просторная деревянная беседка из клееного бруса. Рассчитана на 8–10 человек. Крыша из мягкой черепицы.',
    badge: 'hit',
    rating: 4.7,
    reviews: 89,
    inStock: true,
    features: ['Материал: клееный брус', 'Площадь: 16 м²', 'Вместимость: 10 чел.', 'Сборка включена'],
  },
  {
    id: 4,
    category: 'swings',
    name: 'Качели «Ренессанс»',
    price: 34990,
    oldPrice: null,
    image: 'images/products/004-renesans/img1.jpg',
    images: [
      'images/products/004-renesans/img1.jpg',
      'images/products/004-renesans/img2.jpg',
      'images/products/004-renesans/img3.jpg',
      'images/products/004-renesans/img4.jpg',
    ],
    description: 'Лёгкая разборная беседка с москитной сеткой. Быстрый монтаж без инструментов.',
    badge: '',
    rating: 4.5,
    reviews: 34,
    inStock: true,
    features: ['Москитная сетка', 'Каркас: алюминий', 'Размер: 3×3 м', 'Вес: 8 кг'],
  },
  {
    id: 5,
    category: 'swings',
    name: 'Качели «Империя»',
    price: 12990,
    oldPrice: 16990,
    image: 'images/products/005-imperia/img1.jpg',
    images: [
      'images/products/005-imperia/img1.jpg',
      'images/products/005-imperia/img2.jpg',
      'images/products/005-imperia/img3.jpg',
      'images/products/005-imperia/img4.jpg',
    ],
    description: 'Складной шезлонг с регулируемой спинкой в 5 позициях. Алюминиевый каркас не ржавеет.',
    badge: 'sale',
    rating: 4.6,
    reviews: 112,
    inStock: true,
    features: ['Материал: текстилен', 'Каркас: алюминий', '5 позиций', 'Нагрузка: 150 кг'],
  },
  {
    id: 6,
    category: 'swings',
    name: 'Качели «Империя Люкс»',
    price: 24990,
    oldPrice: null,
    image: 'images/products/006-imperia/img1.jpg',
    images: [
      'images/products/006-imperia/img1.jpg',
      'images/products/006-imperia/img2.jpg',
      'images/products/006-imperia/img3.jpg',
      'images/products/006-imperia/img4.jpg',
    ],
    description: 'Двухместный шезлонг для романтичного отдыха. Регулируемые спинки, съёмный столик.',
    badge: 'new',
    rating: 4.9,
    reviews: 18,
    inStock: true,
    features: ['2 места', 'Столик в комплекте', 'Влагостойкие подушки', 'Раскладной'],
  },
  {
    id: 7,
    category: 'swings',
    name: 'Качели «Амаре»',
    price: 54990,
    oldPrice: 69990,
    image: 'images/products/007-amare/img1.jpg',
    images: [
      'images/products/007-amare/img1.jpg',
      'images/products/007-amare/img2.jpg',
      'images/products/007-amare/img3.jpg',
      'images/products/007-amare/img4.jpg',
    ],
    description: 'Полный комплект садовой мебели: стол, 4 кресла, скамья. Тиковое дерево высшего качества.',
    badge: 'sale',
    rating: 4.8,
    reviews: 56,
    inStock: true,
    features: ['Тик высший сорт', 'Стол + 4 кресла + скамья', 'Подушки в комплекте', 'Гарантия 5 лет'],
  },
  {
    id: 8,
    category: 'swings',
    name: 'Качели «Таити»',
    price: 42990,
    oldPrice: null,
    image: 'images/products/008-taiti/img1.jpg',
    images: [
      'images/products/008-taiti/img1.jpg',
      'images/products/008-taiti/img2.jpg',
      'images/products/008-taiti/img3.jpg',
      'images/products/008-taiti/img4.jpg',
    ],
    description: 'Модульный диванный комплект из искусственного ротанга. 5 модулей, конфигурация на ваш вкус.',
    badge: 'hit',
    rating: 4.7,
    reviews: 73,
    inStock: true,
    features: ['Искусственный ротанг', '5 модулей', 'Ткань Sunbrella', 'Любая конфигурация'],
  },
  {
    id: 9,
    category: 'swings',
    name: 'Качели «Паттайя»',
    price: 4990,
    oldPrice: 6990,
    image: 'images/products/009-pataya/img1.jpg',
    images: [
      'images/products/009-pataya/img1.jpg',
      'images/products/009-pataya/img2.jpg',
      'images/products/009-pataya/img3.jpg',
      'images/products/009-pataya/img4.jpg',
    ],
    description: 'Лёгкий складной стол для пикника и дачи. Алюминиевые ножки, столешница из ЛДСП.',
    badge: 'sale',
    rating: 4.4,
    reviews: 203,
    inStock: true,
    features: ['Размер: 120×60 см', 'Алюминиевые ножки', 'Чехол в комплекте', 'Вес: 5 кг'],
  },
  {
    id: 10,
    category: 'swings',
    name: 'Качели «Ибица Green»',
    price: 19990,
    oldPrice: null,
    image: 'images/products/010-ibitsa-green/img1.jpg',
    images: [
      'images/products/010-ibitsa-green/img1.jpg',
      'images/products/010-ibitsa-green/img2.jpg',
      'images/products/010-ibitsa-green/img3.jpg',
      'images/products/010-ibitsa-green/img4.jpg',
    ],
    description: 'Обеденный стол для террасы и веранды. Нержавеющая сталь + HPL столешница.',
    badge: '',
    rating: 4.9,
    reviews: 31,
    inStock: true,
    features: ['Размер: 160×80 см', 'Каркас: нержавейка', 'HPL столешница', 'Разборный'],
  },
  {
    id: 11,
    category: 'swings',
    name: 'Качели «Барселона»',
    price: 8990,
    oldPrice: 11990,
    image: 'images/products/011-barselona/img1.jpg',
    images: [
      'images/products/011-barselona/img1.jpg',
      'images/products/011-barselona/img2.jpg',
      'images/products/011-barselona/img3.jpg',
      'images/products/011-barselona/img4.jpg',
    ],
    description: 'Плетёное кресло из натурального ротанга. Лёгкое и прочное. Подушка сиденья в комплекте.',
    badge: 'sale',
    rating: 4.6,
    reviews: 88,
    inStock: true,
    features: ['Натуральный ротанг', 'Подушка в комплекте', 'Нагрузка: 120 кг', 'Для улицы и дома'],
  },
  {
    id: 12,
    category: 'dining',
    name: 'Стул складной «Дача»',
    price: 2990,
    oldPrice: null,
    image: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600&q=80',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&q=80',
    ],
    description: 'Практичный складной стул для дачи. Стальной каркас с порошковым покрытием.',
    badge: '',
    rating: 4.2,
    reviews: 341,
    inStock: true,
    features: ['Стальной каркас', 'Порошковое покрытие', 'Нагрузка: 100 кг', 'Компактное хранение'],
  },
  {
    id: 13,
    category: 'terrace',
    name: 'Декинг «Натурал»',
    price: 2490,
    oldPrice: null,
    image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=600&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80',
    ],
    description: 'Террасная доска из ДПК (цена за м²). Имитирует тёплое дерево. Не скользит, не гниёт.',
    badge: 'new',
    rating: 4.7,
    reviews: 62,
    inStock: true,
    features: ['Материал: ДПК', 'Цена за 1 м²', '3 цвета', 'Клипсы в комплекте'],
  },
  {
    id: 14,
    category: 'storage',
    name: 'Ящик садовый «Ларец»',
    price: 7990,
    oldPrice: 9990,
    image: 'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=600&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80',
    ],
    description: 'Вместительный ящик для хранения садового инвентаря. Крышка служит скамейкой.',
    badge: 'sale',
    rating: 4.5,
    reviews: 44,
    inStock: true,
    features: ['Объём: 300 л', 'Крышка-скамья', 'Водонепроницаемый', 'Замок в комплекте'],
  },
  {
    id: 15,
    category: 'storage',
    name: 'Хозблок «Дачник»',
    price: 49990,
    oldPrice: null,
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80',
      'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=600&q=80',
    ],
    description: 'Металлический хозяйственный блок для инструментов. Двойные стенки, утепление.',
    badge: '',
    rating: 4.8,
    reviews: 27,
    inStock: false,
    features: ['Размер: 2×1.5×2 м', 'Утеплённый', 'Металл: 2 мм', 'Монтаж включён'],
  },
];
